// Tailwind v4 safelist for @tailwindcss/vite
// This module is imported from Layout.astro so Tailwind's Oxide scanner discovers
// these class names during build. Without this, utility classes used only in .astro
// templates are tree-shaken because .astro files aren't in Vite's JS module graph.

export const safelist = [
  '-bottom-4', '-top-2', '-translate-x-1/2', 'absolute', 'after:absolute',
  'after:bg-tjb-rose-500', 'after:bottom-0', 'after:duration-300', 'after:h-0.5',
  'after:left-0', 'after:transition-all', 'after:w-0', 'aspect-video',
  'backdrop-blur-sm', 'bg-tjb-charcoal', 'bg-tjb-cream', 'bg-tjb-cream-100',
  'bg-tjb-cream-50', 'bg-tjb-cream/95', 'bg-tjb-lavender-100', 'bg-tjb-lavender-200',
  'bg-tjb-lavender-50', 'bg-tjb-lavender-500', 'bg-tjb-rose-100', 'bg-tjb-rose-50',
  'bg-tjb-rose-500', 'bg-tjb-sage-100', 'bg-white', 'block', 'border', 'border-0',
  'border-2', 'border-b', 'border-l-2', 'border-t', 'border-tjb-gray/20',
  'border-tjb-lavender-100', 'border-tjb-lavender-200', 'border-tjb-lavender-300',
  'border-tjb-lavender-300/20', 'border-tjb-lavender-300/30', 'border-tjb-lavender-300/40',
  'border-tjb-lavender-400', 'border-tjb-lavender-500', 'border-tjb-rose-200',
  'border-tjb-rose-400', 'border-transparent', 'btn-accent', 'btn-primary',
  'btn-secondary', 'curve-bottom', 'dot-grid', 'duration-200', 'duration-300',
  'eyebrow', 'flex', 'flex-1', 'flex-col', 'flex-shrink-0', 'flex-wrap',
  'focus:absolute', 'focus:bg-tjb-charcoal', 'focus:border-tjb-lavender-500',
  'focus:border-tjb-rose-400', 'focus:left-4', 'focus:not-sr-only',
  'focus:outline-none', 'focus:px-4', 'focus:py-2', 'focus:rounded-lg',
  'focus:text-white', 'focus:top-4', 'focus:z-50', 'font-bold', 'font-medium',
  'font-normal', 'font-sans', 'font-semibold', 'font-serif', 'gap-10', 'gap-2',
  'gap-3', 'gap-4', 'gap-6', 'gap-8', 'gap-x-4', 'gap-x-6', 'gap-y-2', 'grid',
  'group', 'group-hover:scale-[1.02]', 'group-hover:text-tjb-rose-500', 'h-0.5',
  'h-10', 'h-12', 'h-16', 'h-4', 'h-48', 'h-56', 'h-6', 'h-64', 'h-8', 'h-auto',
  'h-full', 'hidden', 'hover:after:w-full', 'hover:bg-tjb-cream',
  'hover:bg-tjb-rose-500', 'hover:border-tjb-lavender-500', 'hover:border-tjb-rose-300',
  'hover:border-tjb-rose-500', 'hover:shadow-lg', 'hover:shadow-md',
  'hover:shadow-tjb-lavender-300', 'hover:text-tjb-charcoal',
  'hover:text-tjb-lavender-light', 'hover:text-tjb-rose-500', 'hover:text-tjb-rose-600',
  'hover:underline', 'inline-block', 'inset-0', 'italic', 'items-center',
  'items-start', 'justify-between', 'justify-center', 'leading-[1.12]',
  'leading-[1.15]', 'leading-[1.65]', 'leading-none', 'leading-relaxed', 'leading-tight',
  'left-1/2', 'left-3', 'max-w-2xl', 'max-w-3xl', 'max-w-4xl', 'max-w-5xl',
  'max-w-6xl', 'max-w-md', 'max-w-sm', 'max-w-xl', 'mb-1', 'mb-10', 'mb-12',
  'mb-16', 'mb-2', 'mb-3', 'mb-4', 'mb-5', 'mb-6', 'mb-8', 'md:flex',
  'md:flex-row-reverse', 'md:gap-16', 'md:gap-8', 'md:grid-cols-2',
  'md:grid-cols-3', 'md:grid-cols-4', 'md:grid-cols-[3rem_1fr]', 'md:h-64',
  'md:hidden', 'md:inline-block', 'md:justify-end', 'md:left-5', 'md:left-8',
  'md:order-1', 'md:order-2', 'md:pb-28', 'md:pl-12', 'md:pt-24', 'md:py-14',
  'md:py-20', 'md:py-24', 'md:py-28', 'md:py-32', 'md:text-2xl', 'md:text-3xl',
  'md:text-4xl', 'md:text-xl', 'md:translate-x-0', 'md:w-52', 'min-h-dvh',
  'mt-0.5', 'mt-1', 'mt-1.5', 'mt-12', 'mt-2', 'mt-3', 'mt-4', 'mt-8', 'mt-auto',
  'mx-auto', 'my-10', 'my-6', 'my-8', 'not-prose', 'object-cover', 'overflow-hidden',
  'p-2', 'p-4', 'p-5', 'p-6', 'p-8', 'pb-0.5', 'pb-12', 'pb-16', 'pb-20', 'pb-4',
  'pb-6', 'pl-8', 'prose', 'pt-16', 'pt-20', 'pt-6', 'pt-8', 'px-4', 'px-5',
  'px-6', 'px-8', 'py-10', 'py-12', 'py-16', 'py-2', 'py-2.5', 'py-20', 'py-3',
  'py-3.5', 'py-4', 'py-5', 'py-8', 'relative', 'rounded', 'rounded-2xl',
  'rounded-full', 'rounded-lg', 'rounded-xl', 'select-none', 'shadow-lg',
  'shadow-md', 'shadow-sm', 'shadow-xl', 'shrink-0', 'sm:flex-row', 'sm:grid-cols-2',
  'space-y-0', 'space-y-1', 'space-y-16', 'space-y-2', 'space-y-3', 'space-y-4',
  'space-y-6', 'space-y-8', 'sr-only', 'sticky', 'text-2xl', 'text-3xl', 'text-5xl',
  'text-[0.9375rem]', 'text-[1.0625rem]', 'text-[2.25rem]', 'text-[2.2rem]',
  'text-[2.5rem]', 'text-[8rem]', 'text-center', 'text-left', 'text-lg', 'text-sm',
  'text-tjb-charcoal', 'text-tjb-cream', 'text-tjb-cream/80', 'text-tjb-gray',
  'text-tjb-gray-300', 'text-tjb-gray/70', 'text-tjb-lavender-400',
  'text-tjb-lavender-500', 'text-tjb-lavender-600', 'text-tjb-rose-300',
  'text-tjb-rose-400', 'text-tjb-rose-500', 'text-tjb-sage', 'text-white', 'text-xl',
  'text-xs', 'top-0', 'tracking-wide', 'transition', 'transition-all',
  'transition-colors', 'transition-transform', 'underline', 'underline-offset-3',
  'uppercase', 'w-10', 'w-12', 'w-16', 'w-4', 'w-44', 'w-6', 'w-8', 'w-auto',
  'w-fit', 'w-full', 'whitespace-nowrap', 'z-50',
  'md:text-[1.125rem]', 'md:text-[1.375rem]', 'md:text-[1.75rem]',
  'md:text-[10rem]', 'md:text-[2.75rem]', 'md:text-[3.25rem]', 'md:text-[3rem]',
  'border-[3px]', 'rounded-[60%_40%_50%_50%/40%_50%_50%_60%]',
  'shadow-tjb-lavender-300/20', 'shadow-tjb-lavender-300/40',
];