#!/usr/bin/env python3
"""Insert the pasadena-ca block into src/data/cities.ts (BUILD stage, 2026-09-24)."""
import re

PASADENA = '''  "pasadena-ca": {
    city: "Pasadena" ,
    state: "CA" ,
    slug: "pasadena-ca" ,
    publishedDate: "2026-09-24",
    heroImage: "/images/pasadena-ca-birth-doula-skyline.webp" ,
    ogImage: "https://truejoybirthing.com/images/og-city-pasadena-ca.webp" ,
    enableBlogResources: true,
    supportSceneAlt: "A doula walking alongside an expectant mom beneath the oaks near the Colorado Street Bridge in Pasadena, California, with the San Gabriel Mountains in the distance" ,
    supportSceneImage: "/images/pasadena-ca-support-scene.webp" ,
    midwifeInfo: {
      paragraph: "California licenses both Licensed Midwives (LMs) and Certified Nurse-Midwives (CNMs), with LMs attending home and birth center births and CNMs practicing in hospitals. California Medi-Cal covers doula services through the PAVE program, reimbursing approximately $1,587 per pregnancy. Pasadena families deliver primarily at Huntington Hospital, home to the San Gabriel Valley's only Level III-B NICU and its specialized Small Baby Unit, while USC Arcadia Hospital offers a 17-bed Level III NICU about four miles east. For out-of-hospital birth, Moxie Birth in nearby South Pasadena, the only freestanding birth center in the Los Angeles area founded and operated by both a midwife and an obstetrician, is about two miles from downtown Pasadena." ,
      credentialTypes: " (LMs and CNMs)" ,
      credentialDetail: "California licenses Licensed Midwives (LMs) who attend home and birth center births and Certified Nurse-Midwives (CNMs) who practice in hospitals and birth centers, giving Pasadena families more out-of-hospital midwifery options than states that only license CNMs." },
    costLow: 1500,
    costHigh: 6000,
    shelbiServesHere: false,
    culture: "Pasadena anchors the western San Gabriel Valley with a blend of deep-rooted historic neighborhoods, world-class cultural institutions like the Norton Simon Museum, and a strong natural-birth community that predates most of Los Angeles County. Families here give birth at Huntington Hospital, whose Small Baby Unit pioneered family-integrated NICU care, or cross the bridge to USC Arcadia for high-risk deliveries. A well-established birth community of childbirth educators, lactation consultants, and doulas who have worked the Pasadena circuit for decades means support people here are rarely starting from scratch. The city's walkable older neighborhoods, tree-lined streets, and proximity to the San Gabriel foothills give expectant families genuine third-trimester walking and nesting options, and the Colorado Street Bridge area remains the classic stroll for families waiting on labor." ,
    heroLocalDetail: "At 38 weeks in Pasadena, you're likely mapping the drive to Huntington Hospital on West California Boulevard or USC Arcadia on East Huntington Drive. The 134 and 210 both serve the city, but surface streets like Lake Avenue and Colorado Boulevard often beat the freeway during rush hour. Old Pasadena and the Colorado Street Bridge area offer flat, shady walking for those final weeks, and Huntington's maternity entrance sits just off the 134 Fair Oaks exit, so plan your route at two different times of day before labor starts." ,
    hospitalDetails: [
      { name: "Huntington Hospital" , thumbnail: "/images/pasadena-ca-hospital-huntington.webp" , paragraph: "Huntington Hospital, part of Huntington Health and affiliated with Cedars-Sinai, is Pasadena's flagship maternity hospital with approximately 2,600 to 3,400 deliveries a year, the largest volume in the San Gabriel Valley. Its Level III-B NICU is the most advanced in the San Gabriel Valley, anchored by the Small Baby Unit, a nationally recognized program for infants born before 32 weeks that pioneered family-integrated care, allowing parents to room in and participate in rounds. The maternity program offers private LDR suites, 24/7 in-house obstetricians and anesthesiology, VBAC support, and certified lactation consultants, and doulas are welcomed as support people throughout labor. <a href='/birth-plan-template/'>Use our free hospital birth plan template</a> to prepare for your delivery." , nicuLevel: "III" , doulaPolicy: "Doulas welcome as support persons" , midwifeFriendly: true, waterBirth: "Labor tubs available in some suites" , medicaid: true, lactation: true, privateRooms: true, address: "100 W California Blvd, Pasadena, CA 91105" , url: "https://www.huntingtonhealth.org/services/maternity/" },
      { name: "USC Arcadia Hospital" , thumbnail: "/images/pasadena-ca-hospital-usc-arcadia.webp" , paragraph: "USC Arcadia Hospital, part of Keck Medicine of USC and about four miles from Pasadena, provides full-service maternity care with OB-GYNs, certified nurses, and laborists on call 24/7, plus 24-hour anesthesia coverage for pain management. The hospital supports natural birth, epidural-assisted delivery, and VBAC, with a 17-bed Level III NICU and a visitor policy that welcomes doulas as part of each patient's support plan when coordinated with staff. It's the closest high-acuity option east of Pasadena, handling routine and high-risk pregnancies alike, with a couplet care model that keeps mother and baby together after delivery. <a href='/birth-plan-template/'>Use our free hospital birth plan template</a> to get started." , nicuLevel: "III" , doulaPolicy: "Doulas welcome; check with staff for second-support rules" , midwifeFriendly: true, waterBirth: "Not available" , medicaid: true, lactation: true, privateRooms: true, address: "445 E Huntington Dr, Arcadia, CA 91006" , url: "https://www.keckmedicine.org/centers-and-programs/usc-arcadia-hospital/maternity-care-and-services/" } ],
    birthCenterDetails: [
      { name: "Moxie Birth" , address: "1416 El Centro St, Ste 100, South Pasadena, CA 91030" , url: "https://www.moxiecare.com/birth" , paragraph: "Moxie Birth, about two miles from downtown Pasadena, is the only birth center in the Los Angeles area founded and operated by both a licensed midwife and an obstetrician, pairing midwifery-led out-of-hospital birth with integrated OB consultation. The nationally recognized center offers private birth suites with deep soaking tubs for water birth, personalized 30-minute prenatal visits, lactation support, and continuous midwifery care through birth and the postpartum weeks, with a warm home-like setting and direct hospital transfer relationships if needed. Phone: (626) 399-0649." , thumbnail: "/images/moxie-birth-south-pasadena-v2.webp" , services: ["Water Birth" , "Midwife-Led Care" , "Prenatal Care" , "Postpartum Support"], medicaid: false, distance: "2 miles from Pasadena" } ],
    localDoulas: [
      { name: "Nancy Connelly" , credential: "CD(DONA), Certified Lactation Educator" , practice: "Nancy's Doula Services" , url: "http://www.nancydoula.com/" , photo: "/images/provider-pasadena-ca-nancy-connelly.webp" , description: "DONA-certified birth doula based in Pasadena since 2000 with more than 635 births attended across Pasadena, Arcadia, Altadena, South Pasadena, and the surrounding San Gabriel Valley. A Certified Lactation Educator, Nancy offers two to three prenatal visits, continuous hands-on labor support at your birth, immediate postpartum breastfeeding help, and a follow-up visit, with 24/7 availability for questions from hire through the fourth trimester. Works with families birthing at Huntington Hospital and throughout the region." , services: ["Birth Doula" , "Lactation Support" , "Prenatal Visits" , "Postpartum Visit"], costRange: "$3,000-$3,000" , acceptingClients: true },
      { name: "Brighid Quinn" , credential: "CD-L Birth & Postpartum Doula" , practice: "Quinn Doula Services" , url: "https://www.quinndoula.com/" , photo: "/images/provider-pasadena-ca-brighid-quinn.webp" , description: "Highland Park-based birth and postpartum doula serving Pasadena and the greater Los Angeles area with pragmatic, evidence-based care. Offers a hybrid birth doula option with several prenatal meetings, birth-preference planning, and virtual labor support, or full in-person birth attendance, plus postpartum contracts with several visits a week. Experienced with Hypnobirthing, unmedicated and low-intervention births, VBAC, twins, home and birth center births, and solo parents. Payment plans and a sliding scale are available." , services: ["Birth Doula" , "Postpartum" , "Virtual Labor Support" , "VBAC Support"], costRange: "$2,000-$4,000" , acceptingClients: true },
      { name: "Rebecca Belenky" , credential: "CD, CPD, CBE, CLEC" , practice: "Los Angeles Birth" , url: "https://www.losangelesbirth.com/" , photo: "/images/provider-pasadena-ca-rebecca-belenky.webp" , description: "Certified birth and postpartum doula, childbirth educator, and lactation educator serving Pasadena families since 2014 from her South Pasadena base. Rebecca offers trauma-informed, LGBTQ+-affirming support across hospital, birth center, and home births, with birth doula packages that include three prenatal sessions, hands-on body balancing, on-call labor attendance, and 24-48 hour postpartum lactation visits. She attends births regularly at Huntington Hospital, Moxie Birth Center, UCLA, and Cedars-Sinai, and provides private childbirth education classes in your Pasadena home." , services: ["Birth Doula" , "Postpartum" , "Childbirth Education" , "Lactation Support"], costRange: "$5,000-$6,000" , acceptingClients: true } ],
    medicaidNote: "Yes — California's Medi-Cal program covers doula services as a state benefit, reimbursing approximately $1,587 per pregnancy through the PAVE (Providing Access and Transforming Health) program. Pasadena families on Medi-Cal can access birth and postpartum doula support at no cost by working with an enrolled Medi-Cal doula provider; ask your doula whether they accept Medi-Cal directly." ,
    insuranceNote: "In Pasadena, many families carry private coverage through Anthem Blue Cross, Blue Shield, Kaiser Permanente, or Health Net. Kaiser members can access contracted doula services at no extra cost, and some independent Pasadena doulas, including several who serve Huntington Hospital families, bill Kaiser and Health Net directly. Doula coverage by other private insurers is expanding under California law, and HSA or FSA funds can typically be applied to doula services. Check your plan's maternity benefits and ask doulas for a superbill if you plan to seek reimbursement." ,
    faqs: [
      { q: "How much does a doula cost in Pasadena?" , a: "Pasadena birth doulas typically charge between $1,500 and $6,000. Experienced Pasadena-based doulas like Nancy Connelly charge around $3,000 flat, while premium packages from practices like Los Angeles Birth run $5,000-$6,000 with extensive prenatal and postpartum support. Hybrid and virtual models in the area start near $2,000. The investment typically covers prenatal visits, continuous labor support, and postpartum check-ins. <a href='/birth-plan-template/'>Download your free birth plan template</a> and start planning what matters most to you." },
      { q: "Does Medi-Cal cover doulas in Pasadena?" , a: "Yes. California's Medi-Cal program covers doula services, reimbursing approximately $1,587 per pregnancy through the PAVE program. Enrolled Medi-Cal doulas provide prenatal, labor, and postpartum support at no out-of-pocket cost to qualifying families in Pasadena. <a href='/birth-plan-template/'>Grab the free birth plan template</a> so your doula team knows your preferences." },
      { q: "Which hospitals in Pasadena accommodate birth plans?" , a: "Huntington Hospital, with the San Gabriel Valley's only Level III-B NICU and its specialized Small Baby Unit, welcomes doulas as support people and supports birth plans including VBAC. USC Arcadia Hospital, about four miles east, offers laborists on call 24/7 and also welcomes doulas when coordinated with staff. Both hospitals provide private maternity rooms and lactation support. <a href='/birth-plan-template/'>Grab the free birth plan template</a> so you walk in prepared." },
      { q: "Are there birth centers near Pasadena?" , a: "Yes — Moxie Birth in South Pasadena, about two miles from downtown Pasadena, is the only freestanding birth center in the Los Angeles area founded and operated by both a licensed midwife and an obstetrician, with private suites and deep soaking tubs for water birth. Pasadena families also use Del Mar Birth Center in South Pasadena and home birth with Licensed Midwives. <a href='/birth-plan-template/'>Grab the free birth plan template</a> to think through your options." },
      { q: "Does True Joy Birthing work with Pasadena families?" , a: "True Joy Birthing provides free birth-prep tools for Pasadena families. The Joyful Birth Plan, checklist, and guided walkthrough in the app work for any Pasadena birth setting, whether you're delivering at Huntington Hospital, USC Arcadia, or Moxie Birth. The app also helps you connect with local doulas and midwives in your area." },
      { q: "What about postpartum support in Pasadena?" , a: "Pasadena has strong postpartum resources: hospital-based lactation support at Huntington Hospital, DONA-certified postpartum doulas like Nancy Connelly who hold Certified Lactation Educator credentials, and postpartum doula rates in the area starting around $45 an hour. Start your search during the second trimester if you want ongoing postpartum support. <a href='/blog/postpartum-doula/'>Learn more about postpartum doula support</a>." } ],
    nearbyCities: ["glendale-ca", "los-angeles-ca", "long-beach-ca", "torrance-ca"],
    lat: 34.1478,
    lng: -118.1445,
    birthStats: {
      cesareanRate: 31.0,
      maternalMortalityRate: 12.0,
      homeBirthRate: 2.0,
      birthCenterBirthRate: 1.0,
      dataYear: 2023,
      dataSource: "CDC NCHS, National Vital Statistics System",
    },
},
'''

c = open('src/data/cities.ts').read()
m = re.search(r'^  "spokane-wa":\s*\{', c, re.M)
c2 = c[:m.start()] + PASADENA + c[m.start():]
open('src/data/cities.ts', 'w').write(c2)
print('inserted at', m.start(), 'new length', len(c2))