#!/usr/bin/env python3
"""
TJB City Video Automation — end-to-end pipeline for a single city.
Creates scene data, generates TTS, renders video, uploads to YouTube,
embeds on city page, and deploys.

Usage:
    python3 scripts/city-video-automation.py tacoma-wa
    python3 scripts/city-video-automation.py norfolk-va
"""

import subprocess, sys, os, json, re, shutil, time, math
from pathlib import Path

PROJECT_ROOT = Path(__file__).resolve().parent.parent
REMOTION_DIR = Path.home() / '.openclaw' / 'workspace' / 'Kit' / 'life' / 'brands' / 'TrueJoyBirthing' / 'video' / 'remotion'

MISTRAL_API_KEY = os.environ.get('MISTRAL_API_KEY', '')
SHELBI_VOICE = '331c27cd-1809-43c2-853d-4c167f184670'


def run(cmd, timeout=300, cwd=None, check=True):
    """Run a shell command and return output."""
    result = subprocess.run(cmd, shell=True, capture_output=True, text=True, timeout=timeout, cwd=cwd or str(REMOTION_DIR))
    if check and result.returncode != 0:
        print(f'  ⚠️  Command failed (exit {result.returncode}): {cmd[:120]}')
        print(f'     STDERR: {result.stderr[:500]}')
    return result


def get_city_data(slug):
    """Extract city data from cities.ts."""
    with open(PROJECT_ROOT / 'src' / 'data' / 'cities.ts') as f:
        content = f.read()
    
    # Find city block
    start = content.find(f'"{slug}": {{')
    if start == -1:
        print(f'❌ City {slug} not found in cities.ts')
        sys.exit(1)
    
    i = content.index('{', start)
    i += 1
    depth = 1
    while i < len(content) and depth > 0:
        if content[i] == '{': depth += 1
        elif content[i] == '}': depth -= 1
        i += 1
    block = content[start:i]
    
    # Extract text fields
    def get_field(field_name):
        m = re.search(rf'{field_name}:\s*"([^"]*)"', block)
        return m.group(1) if m else ''
    
    def get_bool(field_name, default=False):
        m = re.search(rf'{field_name}:\s*(true|false)', block)
        if m: return m.group(1) == 'true'
        return default
    
    def get_num(field_name, default=0):
        m = re.search(rf'{field_name}:\s*(\d+)', block)
        return int(m.group(1)) if m else default
    
    city = get_field('city')
    state = get_field('state')
    cost_low = get_num('costLow', 1000)
    cost_high = get_num('costHigh', 3000)
    medicaid_note = get_field('medicaidNote')
    is_medicaid = medicaid_note.lower().startswith('yes') if medicaid_note else False
    
    # Extract hospital names
    h_section = block.split('hospitalDetails:')[1].split(']')[0] if 'hospitalDetails:' in block else ''
    hospitals = re.findall(r'name:\s*"([^"]*)"', h_section)
    
    return {
        'city': city,
        'state': state,
        'slug': slug,
        'cost_low': cost_low,
        'cost_high': cost_high,
        'is_medicaid': is_medicaid,
        'medicaid_note': medicaid_note,
        'hospitals': hospitals[:3],
        'published': get_bool('publishedDate', True),
    }


def create_scene_data(data):
    """Create scene data TypeScript file for Remotion."""
    city = data['city']
    state = data['state']
    slug = data['slug']
    st = {'Colorado': 'CO', 'California': 'CA', 'Virginia': 'VA', 'Washington': 'WA', 'North Carolina': 'NC', 'Texas': 'TX'}.get(data['state'], data['state'][:2].upper())
    has_mc = 'true' if data['is_medicaid'] else 'false'
    
    medicaid_line = f"Colorado's Health First Colorado (Medicaid) reimburses doulas up to $750 per birth. Midwives are covered through managed care plans." if data['is_medicaid'] else f"{data['state']} Medicaid doesn't cover doulas right now. Most doulas offer sliding-scale fees and payment plans."
    
    ts_content = f'''// ════════════════════════════════════════════════════════════════════════════
// {city} — Scene data for the {city}, {st} city guide video
// Auto-generated by city-video-automation.py
// ════════════════════════════════════════════════════════════════════════════

import {{ TJBCityVideoData }} from './types';

export const {slug.replace('-', '_')}Data: TJBCityVideoData = {{
  video_metadata: {{
    title: "{city} Birth Guide: Hospitals, Doulas, Midwives & More",
    city: "{city}",
    state: "{st}",
    slug: "{slug}",
    duration_seconds: 0,
    fps: 30,
    medicaid: {has_mc},
    hasBirthCenter: false,
    hasAppScreenshot: false,
  }},
  scenes: [
    {{
      scene_id: "01_hook",
      scene_type: "tjb_city_hook",
      duration_seconds: 0,
      narration: "Just found out you're pregnant in {city}? Awesome. Now you've got eighty tabs open on hospitals, doulas, midwives, insurance. Let's close every single one of them right now.",
      text_content: {{
        city: "{city}",
        state: "{data['state']}",
        slug: "{slug}",
        subtitle: "Your Birth Planning Guide",
      }},
      image_source: "images/{slug}-birth-doula-skyline.webp",
    }},
    {{
      scene_id: "02_overview",
      scene_type: "tjb_city_bridge",
      duration_seconds: 0,
      narration: "Here's what we're covering in this video: which hospitals welcome doulas and midwives, the doulas and midwives you can work with in {city}, what everything costs including midwifery care, {'how ' + data['state'] + ' Medicaid can help' if data['is_medicaid'] else 'your insurance options'}, and a free app that builds your birth plan step by step. Let's start with where you can deliver.",
      text_content: {{
        city: "{city}",
        state: "{st}",
      }},
    }},
    {{
      scene_id: "03_hospital_1",
      scene_type: "tjb_hospital_card",
      duration_seconds: 0,
      narration: "{city}'s top hospital{'s include' if len(data['hospitals']) > 1 else ' is'} {', '.join(data['hospitals'][:2])}. {'All of them' if len(data['hospitals']) > 1 else 'It'} {'welcome' if len(data['hospitals']) > 1 else 'welcomes'} doulas and have{'s' if len(data['hospitals']) == 1 else ''} NICU support for babies who need extra care.",
      text_content: {{
        hospitalName: "{data['hospitals'][0] if data['hospitals'] else ''}",
        badges: ["Doula-Friendly", "NICU", "Medicaid"],
      }},
      image_source: "images/{slug}-birth-doula-skyline.webp",
    }},
    {{
      scene_id: "04_providers",
      scene_type: "tjb_provider_portrait",
      duration_seconds: 0,
      narration: "{city} has experienced doulas and midwives ready to support you. See who's serving your area — and message them directly — in the app.",
      text_content: {{
        city: "{city}",
      }},
    }},
    {{
      scene_id: "05_app",
      scene_type: "tjb_app_feature",
      duration_seconds: 0,
      narration: "Here's the part every {city} mom should know about. The True Joy Birthing app is completely free — no account, no catch. Nine guided sections walk you through your entire birth plan. You can find and message doulas and midwives near you right inside the app. Then export your plan as a PDF to share with your provider. It's the tool every mom needs in her pocket.",
      text_content: {{
        headline: "Build Your Birth Plan",
        features: [
          "Nine guided sections — hospital preferences, pain management, who's in the room",
          "Find and connect with doulas and midwives near you",
          "Export a PDF to share with your provider",
          "Free. No account needed. Works on iPhone.",
        ],
      }},
    }},
    {{
      scene_id: "06_cost",
      scene_type: "tjb_cost_reveal",
      duration_seconds: 0,
      narration: "Here's the reality: a doula in {city} typically costs ${data['cost_low']:,} to ${data['cost_high']:,}. Most doulas offer payment plans, and some accept Medicaid. Midwifery care runs $5,000 to $8,000 for home birth or birth center care, and many midwives accept insurance. The investment is real, but the support is worth every dollar.",
      text_content: {{
        costRange: "${data['cost_low']:,}–${data['cost_high']:,}",
        label: "Doulas · $1K–$3K · Midwives · $5K–$8K",
        description: "Most doulas offer payment plans. Midwives often accept insurance.",
      }},
    }},
    {{
      scene_id: "07_insurance",
      scene_type: "tjb_insurance_branch",
      duration_seconds: 0,
      narration: "{medicaid_line}. Even if you have private insurance, some plans now include doula benefits — it's worth a call to check. The app has resources to help you navigate your options.",
      text_content: {{
        branch: "{'covers' if data['is_medicaid'] else 'no_coverage'}",
        stateName: "{data['state']}",
      }},
    }},
    {{
      scene_id: "08_cta",
      scene_type: "tjb_city_cta",
      duration_seconds: 0,
      narration: "A birth plan tells your care team exactly what matters to you. You can build yours with the free PDF birth plan, watch our walkthrough series, or use the mobile app. It's all free, and it's all ready for you right now. We'll put the link below.",
      text_content: {{
        city: "{city}",
        slug: "{slug}",
      }},
    }},
  ],
}};
'''
    
    out_path = REMOTION_DIR / 'src' / 'data' / f'{slug}-data.ts'
    with open(out_path, 'w') as f:
        f.write(ts_content)
    print(f'  ✅ Scene data created: src/data/{slug}-data.ts')
    return out_path


def generate_tts(data_file):
    """Generate TTS for all scenes via Mistral Voxtral API."""
    if not MISTRAL_API_KEY:
        print('  ⚠️  No MISTRAL_API_KEY set, skipping TTS')
        return None
    
    # Read scene data to extract narrations
    with open(data_file) as f:
        content = f.read()
    
    scenes = re.findall(r'scene_id: "([^"]+)".*?narration: "([^"]*)"', content, re.DOTALL)
    
    slug = data_file.stem.replace('-data', '')
    audio_dir = REMOTION_DIR / 'public' / 'audio' / slug
    audio_dir.mkdir(parents=True, exist_ok=True)
    
    total_duration = 0.0
    scene_durations = {}
    
    for scene_id, narration in scenes:
        if not narration.strip():
            continue
        
        # Clean escaped characters
        narration = narration.replace('\\n', ' ')
        
        out_wav = audio_dir / f'{scene_id}.wav'
        print(f'    TTS: {scene_id} ({len(narration)} chars)...')
        
        try:
            import requests
            resp = requests.post(
                'https://api.mistral.ai/v1/audio/speech',
                headers={
                    'Authorization': f'Bearer {MISTRAL_API_KEY}',
                    'Content-Type': 'application/json',
                },
                json={
                    'model': 'voxtral-mini-tts-latest',
                    'input': narration,
                    'voice_id': SHELBI_VOICE,
                    'response_format': 'wav',
                },
                timeout=120,
            )
            if resp.status_code != 200:
                print(f'    ⚠️  TTS failed for {scene_id}: HTTP {resp.status_code} - {resp.text[:200]}')
                continue
            
            with open(out_wav, 'wb') as f:
                f.write(resp.content)
            
            # Get actual duration via ffprobe
            dur_result = run(f'ffprobe -v error -show_entries format=duration -of default=noprint_wrappers=1:nokey=1 "{out_wav}"', check=False)
            if dur_result.returncode == 0:
                try:
                    actual_dur = float(dur_result.stdout.strip())
                except ValueError:
                    actual_dur = 0
            else:
                actual_dur = 0
            
            if actual_dur <= 0:
                # Estimate: ~3 chars per second for 150 WPM
                actual_dur = max(len(narration) / 12.0, 3.0)
            
            # Pad to next frame boundary (30fps)
            dur_rounded = math.ceil(actual_dur * 30) / 30.0
            scene_durations[scene_id] = dur_rounded
            
            # Pad the WAV to match
            pad_secs = dur_rounded - actual_dur
            if pad_secs > 0.1:
                padded_wav = audio_dir / f'{scene_id}-padded.wav'
                run(f'ffmpeg -y -i "{out_wav}" -af "apad=pad_dur={pad_secs}" -t {dur_rounded} -ac 2 -ar 48000 "{padded_wav}" >/dev/null 2>&1', check=False)
                # Use padded for concat
                shutil.move(str(padded_wav), str(out_wav))
            
            total_duration += dur_rounded
            print(f'      → {actual_dur:.1f}s (padded to {dur_rounded:.1f}s)')
            
        except Exception as e:
            print(f'    ⚠️  TTS error for {scene_id}: {e}')
            dur_rounded = max(len(narration) / 12.0, 3.0)
            scene_durations[scene_id] = dur_rounded
            total_duration += dur_rounded
    
    # Build master WAV
    wav_files = []
    for scene_id, _ in scenes:
        wav = audio_dir / f'{scene_id}.wav'
        if wav.exists():
            wav_files.append(str(wav))
    
    if wav_files:
        # Create concat file
        concat_list = audio_dir / 'concat.txt'
        with open(concat_list, 'w') as f:
            for w in wav_files:
                f.write(f"file '{w}'\n")
        
        master_wav = audio_dir / 'denver-master.wav'
        run(f'ffmpeg -y -f concat -safe 0 -i "{concat_list}" -c copy "{master_wav}" >/dev/null 2>&1', check=False)
        
        # Verify master duration
        dur_result = run(f'ffprobe -v error -show_entries format=duration -of default=noprint_wrappers=1:nokey=1 "{master_wav}"', check=False)
        master_dur = float(dur_result.stdout.strip()) if dur_result.returncode == 0 and dur_result.stdout.strip() else total_duration
        print(f'  ✅ Master WAV: {master_dur:.1f}s (target: {total_duration:.1f}s, drift: {abs(master_dur - total_duration):.2f}s)')
        
        if abs(master_dur - total_duration) > 0.5:
            # Pad master to match
            pad = total_duration - master_dur
            if pad > 0:
                padded = audio_dir / 'denver-master-padded.wav'
                run(f'ffmpeg -y -i "{master_wav}" -af "apad=pad_dur={pad}" -t {total_duration} "{padded}" >/dev/null 2>&1', check=False)
                shutil.move(str(padded), str(master_wav))
                dur_result = run(f'ffprobe -v error -show_entries format=duration -of default=noprint_wrappers=1:nokey=1 "{master_wav}"', check=False)
                master_dur = float(dur_result.stdout.strip()) if dur_result.returncode == 0 and dur_result.stdout.strip() else total_duration
                print(f'    → Corrected master to {master_dur:.1f}s')
    
    return {
        'total_duration': total_duration,
        'scene_durations': scene_durations,
    }


def update_scene_durations(data_file, timing):
    """Update scene durations in the scene data file after TTS."""
    with open(data_file) as f:
        content = f.read()
    
    # Create scene_id → duration_seconds mapping
    for scene_id, duration in timing['scene_durations'].items():
        dur_str = f'{duration:.2f}'
        # Replace placeholder 'duration_seconds: 0' with actual value for this scene
        # Find the scene by scene_id, then update its duration
        pattern = rf'(scene_id: "{scene_id}".*?duration_seconds: )\d+(\.\d+)?'
        replacement = rf'\g<1>{dur_str}'
        new_content = re.sub(pattern, replacement, content, count=1, flags=re.DOTALL)
        if new_content == content:
            print(f'    ⚠️  Could not update duration for {scene_id}')
        content = new_content
    
    with open(data_file, 'w') as f:
        f.write(content)
    
    # Update total duration in video_metadata
    total = f'{timing["total_duration"]:.2f}'
    content = re.sub(r'(duration_seconds: )\d+(\.\d+)?', rf'\g<1>{total}', content, count=1)
    with open(data_file, 'w') as f:
        f.write(content)
    
    print(f'  ✅ Scene durations updated in {data_file.name}')


def copy_assets(slug):
    """Copy hero image to Remotion public/images directory."""
    hero_src = PROJECT_ROOT / 'public' / 'images' / f'{slug}-birth-doula-skyline.webp'
    dest_dir = REMOTION_DIR / 'public' / 'images'
    dest_dir.mkdir(parents=True, exist_ok=True)
    
    if hero_src.exists():
        shutil.copy2(str(hero_src), str(dest_dir / f'{slug}-birth-doula-skyline.webp'))
        print(f'  ✅ Hero image copied')
    
    # Copy logo SVGs
    for logo in ['logo.svg', 'logo-white.svg', 'icon-mark.svg']:
        src = PROJECT_ROOT / 'public' / 'images' / logo
        if src.exists():
            shutil.copy2(str(src), str(dest_dir / logo))
    
    # Copy app screenshots
    for app in ['tjb-app-dashboard.png', 'tjb-app-birth-plan-builder.png']:
        src = PROJECT_ROOT / 'public' / 'images' / app
        if src.exists():
            shutil.copy2(str(src), str(dest_dir / app))
    
    print(f'  ✅ Assets copied')


def register_composition(slug, data_file):
    """Add the city's composition to Root.tsx."""
    root_path = REMOTION_DIR / 'src' / 'Root.tsx'
    with open(root_path) as f:
        root_content = f.read()
    
    var_name = slug.replace('-', '_') + 'Data'
    import_line = f"import {{ {var_name} }} from './data/{slug}-data';"
    
    if import_line.split('from')[0] in root_content:
        print(f'  ⏭️  Composition already registered')
        return True
    
    # Add import after the denver import
    root_content = root_content.replace(
        "import { denverData, denverFirstTwoScenes } from './data/denver-example';",
        f"import {{ denverData, denverFirstTwoScenes }} from './data/denver-example';\n{import_line}"
    )
    
    # Calculate frames
    total_frames = f"{var_name}.scenes.reduce((s, c) => s + Math.max(Math.round(c.duration_seconds * 30), 1), 0)"
    
    # Add composition after Denver's
    comp_block = f'''
        <Composition
          id="{slug.replace('-', '-')}-City-Guide"
          component={{TJBCityVideo}}
          durationInFrames={{fps * Math.ceil({var_name}.video_metadata.duration_seconds)}}
          fps={{fps}}
          width={{1920}}
          height={{1080}}
          defaultProps={{{{videoData: {var_name}, audioPath: 'audio/{slug}/denver-master.wav'}}}}
        />
'''
    
    root_content = root_content.replace(
        '        <Composition\n          id="Denver-City-Guide"',
        f'{comp_block}        <Composition\n          id="Denver-City-Guide"'
    )
    
    with open(root_path, 'w') as f:
        f.write(root_content)
    
    print(f'  ✅ Composition registered as {slug.replace("-", "-")}-City-Guide')
    return True


def render_video(slug):
    """Render the video via Remotion."""
    comp_id = f'{slug.replace("-", "-")}-City-Guide'
    print(f'  Rendering {comp_id}...')
    
    result = run(
        f'npx remotion render --log=error {comp_id} out/{slug}-city-guide.mp4',
        timeout=600,
        check=False
    )
    
    output = REMOTION_DIR / 'out' / f'{slug}-city-guide.mp4'
    if output.exists():
        size = output.stat().st_size / (1024 * 1024)
        print(f'  ✅ Video rendered: {size:.1f}MB')
        return str(output)
    else:
        print(f'  ❌ Render failed: {result.stderr[:500]}')
        return None


def generate_thumbnail(slug, city, state_code):
    """Generate YouTube thumbnail."""
    result = run(
        f'cd {PROJECT_ROOT} && node scripts/render-yt-thumbnail.cjs {slug} "{city}" "{state_code}"',
        timeout=120,
        check=False
    )
    
    thumb = PROJECT_ROOT / 'public' / 'images' / f'yt-thumb-{slug}.png'
    if thumb.exists():
        print(f'  ✅ YouTube thumbnail generated')
        # Copy to Remotion out/
        shutil.copy2(str(thumb), str(REMOTION_DIR / 'out' / f'yt-thumb-{slug}.png'))
        return True
    else:
        print(f'  ⚠️  Thumbnail generation: {result.stderr[:200]}')
        return False


def upload_to_youtube(slug):
    """Upload to YouTube."""
    result = run(
        f'python3 scripts/upload-youtube.py {slug}',
        timeout=180,
        check=False
    )
    
    if result.returncode == 0:
        # Check for YouTube ID
        id_file = REMOTION_DIR / 'out' / f'{slug}-youtube-id.txt'
        if id_file.exists():
            vid_id = id_file.read_text().strip()
            print(f'  ✅ Uploaded to YouTube: https://youtu.be/{vid_id}')
            return vid_id
        else:
            print(f'  ✅ YouTube upload completed')
            return 'published'
    else:
        print(f'  ⚠️  YouTube upload issue: {result.stderr[:300]}')
        return None


def embed_on_page(slug, video_id, city_name=None):
    """Embed YouTube video on city page."""
    page_path = PROJECT_ROOT / 'src' / 'pages' / 'birth-support' / '[city].astro'
    with open(page_path) as f:
        content = f.read()

    embed_marker = f'youtube-nocookie.com/embed/{video_id}'
    if embed_marker in content:
        print(f'  ⏭️  Video already embedded')
        return True

    # Find the video embed section
    if 'slug ===' in content:
        old_embed = re.search(r'\{/\* Denver video \*/}.*?</section>', content, re.DOTALL)
        if old_embed:
            city = city_name or slug.split('-')[0].title()
            new_embed = f'{{/* {slug} video */}}\n      {{slug === "{slug}" && (\n        <section class="py-12 bg-tjb-cream">\n          <div class="max-w-4xl mx-auto px-6">\n            <div class="text-center mb-8">\n              <p class="eyebrow text-tjb-rose-500 uppercase text-xs font-semibold tracking-widest mb-4">Video guide</p>\n              <div class="w-10 h-0.5 bg-tjb-rose-500 mx-auto mb-6"></div>\n              <h2 class="text-2xl md:text-3xl font-bold text-tjb-charcoal mb-3" style="font-family: \'DM Sans\', sans-serif;">{city} Doula & Birth Plan Guide</h2>\n              <p class="text-tjb-gray max-w-2xl mx-auto">Watch the full city guide — doulas, hospitals, costs, and more, all in under 5 minutes.</p>\n            </div>\n            <div class="aspect-video rounded-xl overflow-hidden shadow-lg bg-black">\n              <iframe width="100%" height="100%" src="https://www.youtube-nocookie.com/embed/{video_id}" title="{city} Doula & Birth Plan Guide" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen loading="lazy"></iframe>\n            </div>\n          </div>\n        </section>\n      )}}\n    '
            content = content.replace(old_embed.group(0), new_embed)

            with open(page_path, 'w') as f:
                f.write(content)
            print(f'  ✅ Video embedded on city page')
            return True

    print(f'  ⚠️  Could not auto-embed video — template may need manual update')
    return False


def update_csv(slug, video_id):
    """Update the CSV to mark video as live."""
    csv_path = Path.home() / '.openclaw' / 'workspace' / 'Kit' / 'life' / 'brands' / 'TrueJoyBirthing' / 'city-priority-list.csv'
    if not csv_path.exists():
        print(f'  ⚠️  CSV not found, skipping status update')
        return
    
    with open(csv_path) as f:
        lines = f.readlines()
    
    new_lines = []
    updated = False
    for line in lines:
        if slug in line and 'Denver-level' in line:
            # Update video_status to 'live'
            parts = line.strip().split(',')
            if len(parts) >= 14:
                parts[13] = 'live'
                new_lines.append(','.join(parts) + '\n')
                updated = True
            else:
                new_lines.append(line)
        else:
            new_lines.append(line)
    
    if updated:
        with open(csv_path, 'w') as f:
            f.writelines(new_lines)
        print(f'  ✅ CSV updated: video_status=live')


def update_og_image(slug):
    """Generate OG image for the city if it doesn't exist or is under 30KB."""
    og_path = PROJECT_ROOT / 'public' / 'images' / f'og-city-{slug}.webp'
    if og_path.exists() and og_path.stat().st_size > 30 * 1024:
        print(f'  ⏭️  OG image exists ({og_path.stat().st_size/1024:.0f}KB)')
        return True
    
    result = run(f'cd {PROJECT_ROOT} && node scripts/render-city-ogs.cjs {slug}', timeout=120, check=False)
    if result.returncode == 0:
        print(f'  ✅ OG image generated')
        return True
    return False


def main():
    slug = sys.argv[1] if len(sys.argv) > 1 else None
    if not slug:
        print('Usage: python3 scripts/city-video-automation.py {slug}')
        print('Example: python3 scripts/city-video-automation.py tacoma-wa')
        sys.exit(1)
    
    print(f'\n🎬 TJB City Video Automation — {slug}')
    print(f'{"="*50}')
    
    # Step 0: Git sync
    print('\n[Step 0] Git sync...')
    run(f'cd {PROJECT_ROOT} && git stash -q 2>/dev/null || true && git pull --rebase origin main && git stash pop -q 2>/dev/null || true', check=False)
    
    # Step 1: Get city data
    print('\n[Step 1] Reading city data...')
    data = get_city_data(slug)
    print(f'  City: {data["city"]}, {data["state"]}')
    print(f'  Cost: ${data["cost_low"]:,}–${data["cost_high"]:,}')
    print(f'  Medicaid: {"Yes" if data["is_medicaid"] else "No"}')
    print(f'  Hospitals: {data["hospitals"][:3]}')
    
    # Step 1.5: Generate OG image if needed
    print('\n[Step 1.5] OG image check...')
    update_og_image(slug)
    
    # Step 2: Create scene data
    print('\n[Step 2] Creating scene data...')
    data_file = create_scene_data(data)
    
    # Step 3: Optimize city images
    print('\n[Step 3] Optimizing images...')
    run(f'cd {PROJECT_ROOT} && python3 scripts/optimize-city-images.py {slug}', timeout=60, check=False)
    
    # Step 3: Copy assets to Remotion
    print('\n[Step 4] Copying assets to Remotion...')
    copy_assets(slug)
    
    # Step 4: Generate TTS
    print('\n[Step 5] Generating TTS narration...')
    timing = generate_tts(data_file)
    
    if timing:
        print('\n[Step 5b] Updating scene durations...')
        update_scene_durations(data_file, timing)
    
    # Step 5: Register composition in Root.tsx
    print('\n[Step 6] Registering composition...')
    register_composition(slug, data_file)
    
    # Step 7: Render video
    print('\n[Step 7] Rendering video (this takes a few minutes)...')
    video_path = render_video(slug)
    
    if not video_path:
        print(f'\n❌ Video render failed for {slug}')
        sys.exit(1)
    
    # Step 8: Generate YouTube thumbnail
    print('\n[Step 8] Generating YouTube thumbnail...')
    st_code = {'Colorado': 'CO', 'California': 'CA', 'Virginia': 'VA', 'Washington': 'WA', 'North Carolina': 'NC'}.get(data['state'], data['state'][:2].upper())
    generate_thumbnail(slug, data['city'], st_code)
    
    # Step 9: Upload to YouTube
    print('\n[Step 9] Uploading to YouTube...')
    video_id = upload_to_youtube(slug)
    
    if not video_id:
        print(f'  ⏭️  YouTube upload skipped or deferred — will need manual follow-up')
    
    # Step 10: Embed on page
    print('\n[Step 10] Embedding video on city page...')
    embed_on_page(slug, video_id or 'PENDING')
    
    # Step 11: Optimize images
    print('\n[Step 11] Final image optimization...')
    run(f'cd {PROJECT_ROOT} && python3 scripts/optimize-city-images.py {slug}', timeout=60, check=False)
    
    # Step 12: Build and deploy
    print('\n[Step 12] Building and deploying...')
    build_result = run(f'cd {PROJECT_ROOT} && rm -rf dist && npm run build', timeout=180, check=False)
    if build_result.returncode == 0:
        print(f'  ✅ Build passed')
        deploy_result = run(f'cd {PROJECT_ROOT} && bash scripts/deploy.sh {slug}', timeout=300, check=False)
        if deploy_result.returncode == 0:
            print(f'  ✅ Deployed!')
        else:
            print(f'  ⚠️  Deploy may need manual check: {deploy_result.stderr[:300]}')
    else:
        print(f'  ❌ Build failed: {build_result.stderr[:300]}')
        sys.exit(1)
    
    # Step 13: Update CSV
    print('\n[Step 13] Updating CSV...')
    update_csv(slug, video_id or 'PENDING')
    
    print(f'\n{"="*50}')
    print(f'✅ {data["city"]}, {st_code} — Complete!')
    if video_id:
        print(f'   YouTube: https://youtu.be/{video_id}')
    print(f'   Page: https://truejoybirthing.com/birth-support/{slug}/')
    print(f'{"="*50}')


if __name__ == '__main__':
    main()