// Cross-city provider registry data for related cities section
// Generated by: python3 ~/.hermes/scripts/tjb-provider-registry.py generate-related-json --output src/data/related-cities.json
// Manual edits will be overwritten on next generation

export interface RelatedCityEntry {
  slug: string;
  sharedProviders: number;
}

// Static import of generated JSON
import relatedCitiesData from './related-cities.json';

/**
 * Get cities that share providers with the given city.
 * Returns an array of { slug, sharedProviders } sorted by shared count descending.
 */
export function getRelatedCities(slug: string): RelatedCityEntry[] {
  const entry = (relatedCitiesData as Record<string, RelatedCityEntry[]>)[slug];
  if (!entry || !Array.isArray(entry)) return [];
  return entry.sort((a, b) => b.sharedProviders - a.sharedProviders);
}